[tool.poetry]
name = "avocet"
version = "0.1.0"
description = ""
authors = ["kuisap"]

[tool.poetry.dependencies]
python = "^3.6"
numpy-stl = "^2.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
