FROM poifull10/ros_melodic

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  ros-melodic-image-transport-plugins ros-melodic-joy ros-melodic-joystick-drivers \
  && rm -rf /var/lib/apt/lists/*

 
