name: console_release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Release
        uses: ./.github/actions/console_ros
        with:
          run-command: ".ci/console_release.sh"
