name: console_debug

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: debug
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Debug
        uses: ./.github/actions/console_ros
        with:
          run-command: ".ci/console_debug.sh"
