name: build_release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        uses: ./.github/actions/console_ros
        with:
          run-command: ".ci/console_build_release.sh"
